apiVersion: v1
kind: ConfigMap
metadata:
  name: s2-config
  resourceVersion: "07062022"
data:
  spring.datasource.host: "svc-97a0c09b-5c1e-4fe3-818d-97d8f588e44f-dml.azr-virginia-2.svc.singlestore.com"
  spring.datasource.singlestore.driver: "jdbc:singlestore"
  spring.datasource.driver: "jdbc:mariadb"
  spring.datasource.database: "mdm"
  spring.datasource.pool.size: "20"
  spring.datasource.port: "3306"
  spring.datasource.connectTimeout: "4000"
