apiVersion : apps/v1
kind: Deployment
metadata:
  name: yuehingyusinglestore 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuehingyusinglestore
  template:
    metadata:
      labels:
        app: yuehingyusinglestore 
    spec:
      containers:
        - name: yuehingyusinglestore 
          image: yycontainerregistry2022.azurecr.io/yuehingyusinglestore
          ports:
          - containerPort: 8080
          env:
            - name: spring.datasource.host
              valueFrom:
                configMapKeyRef:               
                  name: s2-test-config          
                  key: spring.datasource.host
            - name: spring.datasource.singlestore.driver
              valueFrom:
                configMapKeyRef:
                  name: s2-config
                  key: spring.datasource.singlestore.driver
            - name: spring.datasource.driver
              valueFrom:
                configMapKeyRef:
                  name: s2-config
                  key: spring.datasource.driver
            - name: spring.datasource.database
              valueFrom:
                configMapKeyRef:
                  name: s2-config
                  key: spring.datasource.database
            - name: spring.datasource.pool.size
              valueFrom:
                configMapKeyRef:
                  name: s2-config
                  key: spring.datasource.pool.size
            - name: server.port
              valueFrom:
                configMapKeyRef:
                  name: s2-config
                  key: server.port
            - name: spring.datasource.connectTimeout
              valueFrom:
                configMapKeyRef:
                  name: s2-config
                  key: spring.datasource.connectTimeout
            - name: environment.username
              valueFrom:
                secretKeyRef:         
                  name: s2-secret
                  key: environment.username
            - name: environment.password
              valueFrom:
                secretKeyRef:
                  name: s2-secret
                  key: environment.password
                  
